# Generated by Django 4.1 on 2023-03-03 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='fathername',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='firstname',
            new_name='name',
        ),
    ]
